// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoOuP1vNajdb1uh0N9xPNhTSj_bKLoxcY',
    appId: '1:470232267320:web:43034b73b1296e80ba44cd',
    messagingSenderId: '470232267320',
    projectId: 'todo-11332',
    authDomain: 'todo-11332.firebaseapp.com',
    storageBucket: 'todo-11332.appspot.com',
    measurementId: 'G-S7KL288YFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPZsosfWx8OctvEFWKAuGnG_qLodwPlE',
    appId: '1:470232267320:android:ad7c3db548396388ba44cd',
    messagingSenderId: '470232267320',
    projectId: 'todo-11332',
    storageBucket: 'todo-11332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnXEmEQTKYF2AYINcAB0GU3NyThtxaA3o',
    appId: '1:470232267320:ios:e5c58dce4c615824ba44cd',
    messagingSenderId: '470232267320',
    projectId: 'todo-11332',
    storageBucket: 'todo-11332.appspot.com',
    iosClientId: '470232267320-ab1fiq4huulevcmm52gr67j4ntfcspgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnXEmEQTKYF2AYINcAB0GU3NyThtxaA3o',
    appId: '1:470232267320:ios:bebaf8af084f5f52ba44cd',
    messagingSenderId: '470232267320',
    projectId: 'todo-11332',
    storageBucket: 'todo-11332.appspot.com',
    iosClientId: '470232267320-r3qd52d89m08458njbr5h0911ucdg8gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
